/**
 * BackOfficeServicePort.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package it.csi.taif.taifweb.util.service.integration.acta.backofficeservice;

import it.csi.taif.taifweb.util.service.integration.acta.backoffice.ClientApplicationInfo;
import it.csi.taif.taifweb.util.service.integration.acta.backoffice.DettaglioAOOType;
import it.csi.taif.taifweb.util.service.integration.acta.backoffice.DettaglioStrutturaType;
import it.csi.taif.taifweb.util.service.integration.acta.backoffice.PrincipalExtResponseType;
import it.csi.taif.taifweb.util.service.integration.acta.backoffice.PrincipalResponseType;
import it.csi.taif.taifweb.util.service.integration.acta.backoffice.RelazioniStrutturaPropertiesType;

public interface BackOfficeServicePort extends java.rmi.Remote {
    public PrincipalResponseType[] getPrincipal(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.CodiceFiscaleType idUtente, it.csi.taif.taifweb.util.service.integration.acta.common.IdAOOType idAOO, it.csi.taif.taifweb.util.service.integration.acta.common.IdStrutturaType idStruttura, it.csi.taif.taifweb.util.service.integration.acta.common.IdNodoType idNodo) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public PrincipalExtResponseType[] getPrincipalExt(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.CodiceFiscaleType idUtente, it.csi.taif.taifweb.util.service.integration.acta.common.IdAOOType idAOO, it.csi.taif.taifweb.util.service.integration.acta.common.IdStrutturaType idStruttura, it.csi.taif.taifweb.util.service.integration.acta.common.IdNodoType idNodo, ClientApplicationInfo clientApplicationInfo) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.PagingResponseType getDescendants(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, java.lang.String path, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType rootNodeId, java.util.Date date, java.lang.Integer depth, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter, java.lang.Integer maxItems, java.lang.Integer skipCount) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectResponseType[] getObjectParents(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType rootNodeId, java.util.Date date, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public RelazioniStrutturaPropertiesType[] getRelazioniStruttura(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType objectId, java.lang.String ruolo, java.util.Date date, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectResponseType getProperties(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType objectId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectResponseType[] getPropertiesMassive(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType[] identifiers, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public DettaglioAOOType getDettaglioAOO(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.IdAOOType idAOO) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public DettaglioStrutturaType getDettaglioStruttura(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.IdStrutturaType idStruttura) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.QueryableObjectType[] getQueryableObjects(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, java.lang.String service) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectMetadataType[] getQueryableObjectMetadata(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.QueryableObjectType queryableObject, java.lang.String operation) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.PagingResponseType query(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.QueryableObjectType target, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter, it.csi.taif.taifweb.util.service.integration.acta.common.QueryConditionType[] criteria, it.csi.taif.taifweb.util.service.integration.acta.common.NavigationConditionInfoType navigationLimits, java.lang.Integer maxItems, java.lang.Integer skipCount) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
}
