/**
 * SubjectRegistryServicePort.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package it.csi.taif.taifweb.util.service.integration.acta.subjectregistryservice;

public interface SubjectRegistryServicePort extends java.rmi.Remote {
    public IdentificazioneSoggetto creaSoggetto(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, java.lang.String tipologiaCreazione, SoggettoRequest infoRichiestaCreazione) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public AnagraficaGenerica ricercaSoggetto(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, java.lang.String identitaDigitale, java.lang.String codiceFiscale, java.lang.String partitaIva, java.lang.String fonteEsterna, boolean flagPersonaGiuridica) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public AnagraficaSoggetto[] ricercaSoggettoDaFonteEsterna(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, java.lang.String identitaIride, CriteriRicercaSoggetto criteri) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectResponseType getProperties(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType objectId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.SimpleResponseType updateProperties(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType objectId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ChangeTokenType changeToken, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyType[] properties) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.PagingResponseType query(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.QueryableObjectType target, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter, it.csi.taif.taifweb.util.service.integration.acta.common.QueryConditionType[] criteria, it.csi.taif.taifweb.util.service.integration.acta.common.NavigationConditionInfoType navigationLimits, java.lang.Integer maxItems, java.lang.Integer skipCount) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectResponseType[] getPropertiesMassive(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType[] identifiers, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType creaIndirizzo(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType soggettoId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertiesType properties) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.DecodificaType creaCategoriaAnagrafica(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertiesType properties) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
}
