/**
 * ObjectServicePort.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package it.csi.taif.taifweb.util.service.integration.acta.objectservice;

public interface ObjectServicePort extends java.rmi.Remote {
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType createFolder(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, java.lang.String typeId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertiesType properties, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType folderId) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectResponseType getProperties(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType objectId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectResponseType[] getPropertiesMassive(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType[] identifiers, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType createDocument(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, java.lang.String typeId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertiesType properties, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType folderId, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisContentStreamType contentStream) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType createAssociativeDocument(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, java.lang.String typeId, java.lang.String associativeObjectTypeId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertiesType properties, it.csi.taif.taifweb.util.service.integration.acta.common.PropertiesType associativeObjectProperties, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType folderId, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisContentStreamType contentStream) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType createRelationship(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, java.lang.String typeId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertiesType properties, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType sourceObjectId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType targetObjectId) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.AcarisContentStreamType[] getContentStream(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType documentId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, java.lang.String streamId) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.SimpleResponseType addRenditionStream(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType documentId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ChangeTokenType changeToken, java.lang.String streamId, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisContentStreamType[] contentStream) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.SimpleResponseType updateProperties(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType objectId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ChangeTokenType changeToken, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyType[] properties) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.SimpleResponseType setContentStream(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType documentId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.ChangeTokenType changeToken, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisContentStreamType contentStream) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.PagingResponseType query(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.QueryableObjectType target, it.csi.taif.taifweb.util.service.integration.acta.common.PropertyFilterType filter, it.csi.taif.taifweb.util.service.integration.acta.common.QueryConditionType[] criteria, it.csi.taif.taifweb.util.service.integration.acta.common.NavigationConditionInfoType navigationLimits, java.lang.Integer maxItems, java.lang.Integer skipCount) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public void moveDocument(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId, it.csi.taif.taifweb.util.service.integration.acta.common.holders.ObjectIdTypeHolder associativeObjectId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType sourceFolderId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType targetFolderId, it.csi.taif.taifweb.util.service.integration.acta.common.PropertiesType associativeProperties) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
    public it.csi.taif.taifweb.util.service.integration.acta.common.SimpleResponseType closeFolder(it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType repositoryId, it.csi.taif.taifweb.util.service.integration.acta.common.ObjectIdType objectId, it.csi.taif.taifweb.util.service.integration.acta.common.PrincipalIdType principalId) throws java.rmi.RemoteException, it.csi.taif.taifweb.util.service.integration.acta.common.AcarisFaultType;
}
